Repository wecode-bootcamp-korea/14-2nd-SUWEE-frontend, pull requests merged in 2020-12, with the labels that each got.

#3 [류지혜] NavTop UI 구현
  package-lock.json
  package.json
  public/images/logo_dark.png
  public/images/logo_yellow.png
  public/index.html
  src/Components/Nav/Nav.js
  src/Routes.js
  src/Styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#4 [류지혜] Footer 구현
  .gitignore
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Routes.js
  src/Styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#2 [신세원]Feature/sign up 회원가입 레이아웃 구현 중
  src/Pages/Login/Login.jsx
  src/Pages/SignUp/Agreement/Agreement.jsx
  src/Pages/SignUp/PasswordFind/FindResidentNumber.jsx
  src/Pages/SignUp/PasswordRegister/PasswordRegister.jsx
  src/Pages/SignUp/SignUpPhoneCertify/PhoneCertify.jsx
  src/config.js
  src/data.js
Labels: Status: Accepted

#6 [류지혜] 메인페이지 UI/기능구현 중
  package-lock.json
  package.json
  public/data/bookData.json
  public/data/recommendedBookData.json
  public/images/carousel1.png
  public/images/carousel2.png
  public/images/carousel3.png
  public/images/picture4.jpg
  public/images/profile.png
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Pages/BookDetails/BookDetails.js
  src/Pages/BookRoom/BookRoom.js
  src/Pages/SuweeMain/BestSeller/BestSeller.js
  src/Pages/SuweeMain/CommingSoonBook/CommingSoonBook.js
  src/Pages/SuweeMain/MainImageCarousel/MainImageCarousel.js
  src/Pages/SuweeMain/MainImageCarousel/MainImageCarousel.scss
  src/Pages/SuweeMain/NewBook/NewBook.js
  src/Pages/SuweeMain/RecommendedBook/RecommendedBook.js
  src/Pages/SuweeMain/SuweeMain.js
  src/Pages/SuweeMain/TodaysBook/TodaysBook.js
  src/Pages/SuweeMain/TodaysBook/TodaysBook.scss
  src/Pages/SuweeMain/mainData.js
  src/Routes.js
  src/Styles/CommonStyle.js
  src/Styles/GlobalStyle.js
  src/Styles/Theme.js
  src/config.js
Labels: Status: 리뷰 요청

#9 [신세원] feature/Pay 기능 구현 리뷰 반영 수정완료
  src/Components/InputBox/InputBox.jsx
  src/Components/InputBox/InputBox1.jsx
  src/Components/InputBox/InputBox2.jsx
  src/Components/PhoneCertifyBox/PhoneCertifyBox.jsx
  src/Components/ResidentNumber/ResidentNumber.jsx
  src/Components/SignUpNav/SignUpNav.jsx
  src/Components/Timer/Timer.jsx
  src/Pages/Login/Login.jsx
  src/Pages/Payment/AgreementMiniBox/AgreementMiniBox.jsx
  src/Pages/Payment/Pay/PayAmount.jsx
  src/Pages/Payment/Pay/PayWay.jsx
  src/Pages/SignUp/PasswordRegister/PasswordRegister.jsx
  src/Pages/SignUp/SignUp.jsx
  src/config.js
Labels: Status: 리뷰 요청

#8 [신세원] feature/LandingPage 레이아웃 및 기능 구현중
  package-lock.json
  package.json
  public/data/BOOK_MOCK_DATA.json
  public/images/firstBook.svg
  public/images/name.svg
  public/images/secondBook.svg
  public/images/thirdBook.svg
  public/images/universe.jpg
  public/images/viewer.png
  public/index.html
  src/Components/TitleText/TitleText.jsx
  src/Pages/LandingPage/Component/BookCard/AudioBookCard.jsx
  src/Pages/LandingPage/Component/BookCard/BookCard.jsx
  src/Pages/LandingPage/Component/BookCard/ChatBookCard.jsx
  src/Pages/LandingPage/Component/BookCard/Tiket.jsx
  src/Pages/LandingPage/Component/BookList/Book.jsx
  src/Pages/LandingPage/Component/BookList/BookList.jsx
  src/Pages/LandingPage/Component/BottomText.jsx
  src/Pages/LandingPage/Component/FifthView.jsx
  src/Pages/LandingPage/Component/FirstView.jsx
  src/Pages/LandingPage/Component/FourthView.jsx
  src/Pages/LandingPage/Component/LeftSideText/FifthLeftSideText.jsx
  src/Pages/LandingPage/Component/LeftSideText/LeftSideText.jsx
  src/Pages/LandingPage/Component/SecondView.jsx
  src/Pages/LandingPage/Component/ThirdView.jsx
  src/Pages/LandingPage/Component/ViewBox.jsx
  src/Pages/LandingPage/LandingPage.jsx
  src/Routes.js
  src/Styles/CommonStyle.js
  src/Styles/Theme.js
  src/Styles/themes.js
  src/data.js
Labels: Status: Accepted

#12 [신세원]feature/SignUp 불필요한 inputbox 삭제완료
  src/Pages/SignUp/SignUp.jsx
Labels: Status: Accepted

#10 [신세원] feature/Search 메인 화면 검색기능 구현중
  public/data/BOOK_LIST_MOCK_DATA.json
  src/Components/Nav/Book/Book.jsx
  src/Components/Nav/Nav.js
  src/Components/Nav/SearchNav.jsx
  src/Pages/SuweeMain/BestSeller/BestSeller.js
  src/Pages/SuweeMain/SuweeMain.js
Labels: Status: 리뷰 요청

#11 [류지혜] Feature/BookRoom 내 서재 기능 구현
  public/data/BookRoomData.json
  public/data/BookRoomStatisticData.json
  public/data/BookRoomUserData.json
  public/images/bookRoomBanner.png
  public/images/보노보노.jpeg
  src/Components/Nav/Nav.js
  src/Pages/BookRoom/BookRoom.js
  src/Pages/BookRoom/BookRoomTab/BookRoomTab.js
  src/Pages/BookRoom/BookRoomTab/PickedBooks.js
  src/Pages/BookRoom/BookRoomTab/Statistic.js
  src/Pages/BookRoom/BookRoomTab/bookroomData.js
  src/Pages/BookRoom/UserProfile.js
  src/Pages/SignUp/SignUp.jsx
  src/Pages/SuweeMain/BestSeller/BestSeller.js
  src/Routes.js
  src/Styles/Theme.js
  src/config.js
Labels: Status: 리뷰 요청

#13 [신세원] feature/LandingPage 기능구현 작업완료
  src/Components/Nav/Nav.js
  src/Pages/LandingPage/Component/BookCard/Tiket.jsx
  src/Pages/LandingPage/LandingPage.jsx
  src/Pages/Login/Login.jsx
  src/Pages/Payment/Payment.jsx
  src/Pages/SignUp/Agreement/Agreement.jsx
  src/Pages/SignUp/SignUp.jsx
  src/Pages/SuweeMain/SuweeMain.js
  src/Routes.js
  src/data.js
Labels: Status: 리뷰 요청

#5 [공주민] Detail Page 레이아웃 구현 중
  .gitignore
  package-lock.json
  package.json
  public/data/data.json
  public/images/11.jpg
  public/images/alladin.png
  public/images/book.png
  public/images/checked.png
  public/images/clock.png
  public/images/down-arrow.png
  public/images/heart.png
  public/images/heart1.png
  public/images/imgbox.png
  public/images/library.png
  public/images/question.png
  public/images/review.png
  public/images/rightArrow.png
  public/images/second.png
  public/images/share.png
  public/images/userimage1.jpeg
  public/images/write.png
  public/index.html
  src/Components/Nav/Nav.js
  src/Pages/BookDetails/Aside.js
  src/Pages/BookDetails/BookDetails.js
  src/Pages/BookDetails/Comment.js
  src/Pages/BookDetails/CommentPage.js
  src/Pages/BookDetails/Component/CommentBox.js
  src/Pages/BookDetails/Component/Comments.js
  src/Pages/BookDetails/Component/HalfDoughnut.js
  src/Pages/BookDetails/FirstSection.js
  src/Pages/BookDetails/IntroduceBook.js
  src/Pages/BookDetails/SecondSection.js
  src/Pages/LandingPage/LandingPage.jsx
  src/Pages/SignUp/SignUp.jsx
  src/Routes.js
  src/Styles/CommonStyle.js
  src/Styles/GlobalStyle.js
  src/config.js
  src/data.js
  src/index.js
Labels: Status: 수정 요청, Status: 컨플릭트 해결 요청

#14 [류지혜] Add : main page 추가
  public/images/carousel1.png
  public/images/carousel2.png
  public/images/carousel3.png
  public/images/carousel4.png
  src/Components/Nav/Nav.js
  src/Pages/BookRoom/BookRoom.js
  src/Pages/BookRoom/BookRoomTab/PickedBooks.js
  src/Pages/BookRoom/BookRoomTab/Statistic.js
  src/Pages/BookRoom/BookRoomTab/bookroomData.js
  src/Pages/BookRoom/UserProfile.js
  src/Pages/SuweeMain/BestSeller/BestSeller.js
  src/Pages/SuweeMain/CommingSoonBook/CommingSoonBook.js
  src/Pages/SuweeMain/MainImageCarousel/MainImageCarousel.js
  src/Pages/SuweeMain/MainImageCarousel/MainImageCarousel.scss
  src/Pages/SuweeMain/NewBook/NewBook.js
  src/Pages/SuweeMain/RecommendedBook/RecommendedBook.js
  src/Pages/SuweeMain/SuweeMain.js
  src/Pages/SuweeMain/TodaysBook/TodaysBook.js
  src/Pages/SuweeMain/mainData.js
  src/Styles/Theme.js
  src/config.js
Labels: Status: 컨플릭트 해결 요청
